server:
  port: 6767

netty:
  gRPC:
    port: 8083

thread:
  pool:
    corePoolSize: 200
    maxPoolSize: 500
    queueCapacity: 200


spring:
  data:
    mongodb:
      uri: mongodb://rainbow.milchstrabe.com:37017/rainbow
  redis:
    database: 0
    host: rainbow.milchstrabe.com
    port: 16379
    # password: 123456
    max-active: 10
    max-wait: 500
    max-idle: 5
    min-idle: 1
    timeout: 2000

# ===================================================================
# fastdfs config
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:
    width: 150
    height: 150
  tracker-list:            #TrackerList , support multi
#    - 192.168.1.118:22122
     - rainbow.milchstrabe.com:22122