node:
  host: 127.0.0.1

netty:
  tcp:
    port: 8081
  udp:
    port: 8082
  gRPC:
    port: 8083

curator:
  retryCount: 5
  elapsedTimeMs: 5000
  connectString: rainbow.milchstrabe.com:22181
  sessionTimeoutMs: 60000
  connectionTimeoutMs: 5000


spring:
  data:
    mongodb:
      uri: mongodb://rainbow.milchstrabe.com:37017/rainbow
  redis:
    database: 0
    host: rainbow.milchstrabe.com
    port: 16379
       # password: 123456
    max-active: 10
    max-wait: 500
    max-idle: 5
    min-idle: 1
    timeout: 2000
#    sentinel:
#      master: mymaster
#      nodes: 127.0.0.1:26379?