server:
  servlet:
    application-display-name: skyblue


netty:
  tcp:
    port: 8081
  udp:
    port: 8082
  gRPC:
    port: 8083

curator:
  retryCount: 5
  elapsedTimeMs: 5000
  connectString: 10.40.3.165:2181
  sessionTimeoutMs: 60000
  connectionTimeoutMs: 5000


spring:
  data:
    mongodb:
      uri: mongodb://10.40.3.165:27017/sas_multi_dev
  redis:
    database: 0
    host: 10.40.3.165
    port: 6379
    #    password: 123456
    max-active: 10
    max-wait: 500
    max-idle: 5
    min-idle: 1
    timeout: 2000
#    sentinel:
#      master: mymaster
#      nodes: 127.0.0.1:26379?